site_name: GeoCat Products
theme:
  name: material
  custom_dir: overrides
  logo: assets/LogoOnly.svg
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue

      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      base_path: docs/files
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.keys
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference

copyright: Copyright &copy; 2022 GeoCat BV

plugins:
  - search
  - inline-svg

extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/geocatbv
      name: GeoCat on Facebook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/geocat_bv
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/geocat_bv

# Page tree
nav:
  - Home: index.md
  - Enterprise:
    - bridge.md
    - gne.md