site_name: GeoCat Products
# site_description: GeoCat is pleased to offer our customers an enterprise distribution of GeoNetwork offering a long-term-support, additionals schema plugins, a clean visual appearance, backed by our friendly commercial support.
# site_dir: target/html
# site_url:  !ENV [SITE_URL, 'https://www.geocat.net/docs/geonetwork-enterprise/']

# Repository
# repo_name: core-geonetwork
# repo_url: https://github.com/geonetwork/core-geonetwork
# edit_uri: edit/main/docs/manual/docs

theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/geocat-logo-notext-white.svg
  favicon: assets/geocat-logo-notext.png
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue

      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - content.action.view
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - announce.dismiss

  font:
    text: Roboto
    code: Roboto Mono

# Copyright
copyright: Copyright &copy; 2001 - 2023 GeoCat BV

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      base_path: docs/files
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.keys
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference

plugins:
  - search
  - inline-svg

extra:
  version:
    provider: mike
    default: stable
  # redirect the logo link to another page, not to the home of the docs
  # homepage: https://geonetwork-opensource.org/
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/geocatbv
      name: GeoCat on Facebook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/geocat_bv
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/geocat_bv

# Page tree
nav:
  - Home: index.md
  - Enterprise:
    - bridge.md
    - gne.md